
"""job_tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15mquxCiWfZSTepbgREzdGb5awRGT7Dte
"""

import csv
import os

FILE_NAME = "applications.csv"


def create_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, "w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["Company", "Job Role", "Date", "Status"])


def add_application():
    company = input("Enter company name: ")
    role = input("Enter job role: ")
    date = input("Enter application date (DD-MM-YYYY): ")
    status = input("Enter status (Applied/Interview/Selected/Rejected): ")

    with open(FILE_NAME, "a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([company, role, date, status])

    print("\nApplication added successfully!")


def view_applications():
    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)
        data = list(reader)

    if len(data) <= 1:
        print("\nNo applications found.")
        return

    print("\n========== JOB APPLICATIONS ==========")

    for row in data:
        print(
            f"Company: {row[0]} | "
            f"Role: {row[1]} | "
            f"Date: {row[2]} | "
            f"Status: {row[3]}"
        )


def search_application():
    search = input("Enter company name to search: ").lower()

    found = False

    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)

        next(reader)

        for row in reader:
            if search in row[0].lower():
                print(
                    f"\nCompany: {row[0]}\n"
                    f"Role: {row[1]}\n"
                    f"Date: {row[2]}\n"
                    f"Status: {row[3]}"
                )
                found = True

    if not found:
        print("\nNo application found.")


def update_status():
    company = input("Enter company name: ").lower()

    rows = []

    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)
        rows = list(reader)

    found = False

    for row in rows[1:]:
        if row[0].lower() == company:
            new_status = input(
                "Enter new status "
                "(Applied/Interview/Selected/Rejected): "
            )

            row[3] = new_status
            found = True
            break

    if found:
        with open(FILE_NAME, "w", newline="") as file:
            writer = csv.writer(file)
            writer.writerows(rows)

        print("\nStatus updated successfully!")
    else:
        print("\nCompany not found.")


def delete_application():
    company = input("Enter company name to delete: ").lower()

    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)
        rows = list(reader)

    new_rows = [rows[0]]
    found = False

    for row in rows[1:]:
        if row[0].lower() == company:
            found = True
        else:
            new_rows.append(row)

    if found:
        with open(FILE_NAME, "w", newline="") as file:
            writer = csv.writer(file)
            writer.writerows(new_rows)

        print("\nApplication deleted successfully!")
    else:
        print("\nCompany not found.")


def main():
    create_file()

    while True:

        print("\n========== JOB APPLICATION TRACKER ==========")
        print("1. Add Application")
        print("2. View Applications")
        print("3. Search Application")
        print("4. Update Status")
        print("5. Delete Application")
        print("6. Exit")

        choice = input("\nEnter your choice: ")

        if choice == "1":
            add_application()

        elif choice == "2":
            view_applications()

        elif choice == "3":
            search_application()

        elif choice == "4":
            update_status()

        elif choice == "5":
            delete_application()

        elif choice == "6":
            print("\nThank you for using Job Application Tracker!")
            break

        else:
            print("\nInvalid choice. Please try again.")


main()
